version: 0.0
os: linux
files:
  - source: target/yourappwordcounter.jar
    destination: /home/ec2-user/
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
